### ISSUE TITLE
Suggestion: rename 'media' to 'static' and move all files to 'widgetry' folder

### ISSUE THREAD

**Issue by kmike** [stefanfoulis/django-widgetry#4]
In order to be compatible with conventions established by django.contrib.staticfiles from upcoming django 1.3.

For example, django-admin-tools and django-markitup are now shipping static files in 2 duplicate folders (media and static) because they were using 'media' name and now have to keep it because of backward compatibility - it's better to rename 'media' sooner ;)

**Comment by stefanfoulis** [comment]
I agree :-)
